export type ModuleStory = {
  campaign: "FOUNDATIONS" | "RECON" | "WEB" | "CAPSTONE";
  campaignName: string;
  mission: string;
  briefing: string;
  evidence: string;
  outcome: string;
  defense: string;
  objectives: Record<string, string>;
};

const stories: Record<string, ModuleStory> = {
  "roe-lab-ops": { campaign: "FOUNDATIONS", campaignName: "Range Foundations", mission: "Confirm the engagement boundary", briefing: "You have joined the response team for Northstar Health. Before touching a target, prove that the written authorization, time window, and approved assets agree.", evidence: "The simulated organization's published security contact material.", outcome: "Create a defensible scope record before technical work begins.", defense: "Use written authorization, target allowlists, and an evidence log for every assessment.", objectives: { "scope-proof": "Recover the authorized scope token from the training security notice" } },
  "passive-footprint": { campaign: "RECON", campaignName: "Recon & Enumeration", mission: "Map Northstar's public footprint", briefing: "A newly acquired service is about to be reviewed. Start with public artifacts only and identify what the release process accidentally revealed.", evidence: "Published pages and metadata from the simulated public service.", outcome: "Turn passive findings into a focused, authorized next step.", defense: "Remove sensitive comments and build metadata before a public release.", objectives: { "metadata-proof": "Identify the build codename exposed in published metadata" } },
  "dns-certificate-trail": { campaign: "RECON", campaignName: "Recon & Enumeration", mission: "Trace an overlooked service alias", briefing: "The public inventory does not mention a legacy admin service. Follow DNS and certificate clues to explain why it is connected to the environment.", evidence: "DNS records and certificate names within the simulated range.", outcome: "Build an asset relationship map rather than guessing at hosts.", defense: "Maintain an asset inventory and avoid names that disclose privileged service roles.", objectives: { "dns-proof": "Find the service alias that exposes the administration banner" } },
  "active-service-mapping": { campaign: "RECON", campaignName: "Recon & Enumeration", mission: "Validate the exposed service map", briefing: "The passive picture suggests one exposed application. Use a minimal authorized scan to confirm ports, services, and the next piece of evidence.", evidence: "Only the approved gateway and recon-node targets.", outcome: "Use focused active recon that stays inside the agreed scope.", defense: "Restrict ingress, remove unused services, and separate the management plane.", objectives: { "service-proof": "Identify the approved port and recover its service token" } },
  "http-fingerprinting": { campaign: "RECON", campaignName: "Recon & Enumeration", mission: "Read the service behavior", briefing: "The edge service is reachable, but its technology stack is unknown. Inspect ordinary HTTP behavior and distinguish useful evidence from noise.", evidence: "Headers, cookies, redirects, and responses from the range gateway.", outcome: "Create a test hypothesis from observable application behavior.", defense: "Remove diagnostic headers and return consistent production error responses.", objectives: { "header-proof": "Find the diagnostic header that should not be exposed" } },
  "content-discovery": { campaign: "RECON", campaignName: "Recon & Enumeration", mission: "Find the released backup", briefing: "A release engineer reports a missing configuration change. Search only the authorized web target for files that were accidentally shipped outside the normal index.", evidence: "The application's permitted route space and release artifacts.", outcome: "Document a concrete exposure without expanding the scan beyond scope.", defense: "Keep backups out of deployments and block dotfiles and build artifacts at the web tier.", objectives: { "backup-proof": "Recover the configuration backup exposed by the release" } },
  "auth-enumeration": { campaign: "RECON", campaignName: "Recon & Enumeration", mission: "Explain the login signal", briefing: "Support suspects that a public login page leaks account information. Compare safe, limited requests and determine whether its behavior confirms a known user.", evidence: "The simulated login form and its error and timing behavior.", outcome: "Recognize account enumeration without attempting password attacks.", defense: "Use uniform failure responses, rate limits, and monitoring for repeated login probes.", objectives: { "auth-proof": "Confirm an existing username through the permitted response difference" } },
  "idor-bola": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Review an object authorization flaw", briefing: "The discovered account belongs to a customer portal. Test whether changing an object reference lets an authorized user access another customer's record.", evidence: "A training account and its intentionally vulnerable portal record.", outcome: "Demonstrate broken object-level authorization with a minimal proof.", defense: "Authorize every object request server-side and prefer opaque identifiers as defense in depth.", objectives: { "idor-proof": "Read another user's record through an altered object reference" } },
  "sql-injection": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Prove an unsafe login query", briefing: "A legacy internal login was found during portal review. Test the simulator to show how unsafe query construction can bypass an intended authentication check.", evidence: "The range's simulated legacy login form.", outcome: "Recognize the evidence of injection and the need for parameterized queries.", defense: "Use parameterized queries and least-privilege database accounts.", objectives: { "sqli-proof": "Bypass the simulated login with a boolean expression" } },
  "command-injection": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Test an unsafe command parser", briefing: "An operations helper turns a form value into a system action. The range simulates its parser so you can show why shell metacharacters must never reach command execution.", evidence: "The simulator's constrained command parsing behavior.", outcome: "Identify command injection without executing host operating-system commands.", defense: "Avoid shells, use structured APIs, and enforce strict argument allowlists.", objectives: { "cmd-proof": "Make the simulator accept a second command through its parser" } },
  "cross-site-scripting": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Locate an unsafe output sink", briefing: "A feedback feature reflects customer input into an internal review page. Determine whether input is treated as text or executable browser context.", evidence: "The simulated feedback response and its output context.", outcome: "Connect reflected input to a specific client-side execution risk.", defense: "Encode for the output context, sanitize HTML where needed, and enforce a content security policy.", objectives: { "xss-proof": "Create a script context in the simulator response" } },
  "csrf-session": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Challenge an unprotected state change", briefing: "A profile change endpoint appears to trust browser cookies alone. Demonstrate the missing intent check with the range's safe, contained account action.", evidence: "The training account's state-changing request flow.", outcome: "Separate authentication from proof that a user intended a change.", defense: "Use POST, CSRF tokens, SameSite cookies, and origin validation together.", objectives: { "csrf-proof": "Trigger the simulated state change without a CSRF token" } },
  "ssrf-pivot": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Investigate a server-side fetcher", briefing: "A URL preview feature can reach services that a browser cannot. Use the range's allowlisted paths to prove an internal fetch risk without touching real infrastructure.", evidence: "The simulator's URL fetcher and its internal-only service.", outcome: "Show how server-side trust boundaries differ from browser boundaries.", defense: "Apply canonical URL allowlists, DNS/IP validation, and default-deny egress.", objectives: { "ssrf-proof": "Read the internal proof through the simulated fetcher" } },
  "path-traversal-lfi": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Review unsafe file selection", briefing: "A document viewer accepts a filename parameter. Test whether its path handling can escape the intended directory inside the simulated application.", evidence: "The range document viewer and its approved sample files.", outcome: "Demonstrate why normalization alone is not enough for file access control.", defense: "Use server-side file IDs or canonicalized paths checked against a fixed base directory.", objectives: { "traversal-proof": "Read the simulated secret using a traversal sequence" } },
  "insecure-file-upload": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Assess an upload validator", briefing: "A customer upload feature accepts files based on their extension. Test the simulator to determine whether its validation is strong enough to protect the application.", evidence: "The training upload endpoint and its validation feedback.", outcome: "Explain why extension-only validation creates a release risk.", defense: "Allowlist formats, inspect content, rename uploads, and store them outside executable web roots.", objectives: { "upload-proof": "Pass the simulated validation with a double-extension file" } },
  "jwt-mass-assignment": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Test client-controlled identity claims", briefing: "A new API trusts role data that should be assigned on the server. Validate whether a crafted token or request field changes the account's authority.", evidence: "The range's API token and profile-update simulator.", outcome: "Separate user-provided data from server-owned authorization state.", defense: "Pin token algorithms and keys; map request DTOs through explicit field allowlists.", objectives: { "jwt-proof": "Escalate the simulated role through an unsigned token or request field" } },
  "business-logic": { campaign: "WEB", campaignName: "Web Exploitation & Defense", mission: "Break a checkout invariant", briefing: "The final storefront review has no injection point. Instead, trace its business rules and show how an impossible order total can be accepted.", evidence: "The simulated cart and checkout calculations.", outcome: "Treat business rules as security controls that need server-side enforcement.", defense: "Validate invariants on the server and use idempotency controls for sensitive operations.", objectives: { "logic-proof": "Create a simulated checkout with an impossible negative total" } },
  "capstone-chain": { campaign: "CAPSTONE", campaignName: "Incident Campaign", mission: "Close the Quiet Route investigation", briefing: "Northstar's review team needs a final incident narrative. Chain the earlier recon, authorization, and internal-fetch findings into a single controlled proof, then document the remediation result.", evidence: "Artifacts already discovered across the Northstar training range.", outcome: "Explain the attack path and the defenses that would break it at multiple points.", defense: "Combine asset inventory, object authorization, egress policy, and centralized telemetry.", objectives: { "chain-proof": "Combine the three required artifacts to unlock the final proof", "report-proof": "Recover the remediation receipt that closes the incident report" } },
};

const fallback: ModuleStory = { campaign: "FOUNDATIONS", campaignName: "Learning Path", mission: "Complete the authorized training objective", briefing: "Work only inside the RECON//LAB range and collect evidence for the stated objective.", evidence: "The selected training target.", outcome: "Record a safe, repeatable finding.", defense: "Document the risk and recommend a least-privilege control.", objectives: {} };

export function storyFor(labId: string): ModuleStory { return stories[labId] ?? fallback; }
